services:
  - type: web
    name: gcs-image-api
    runtime: python
    buildCommand: ""
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: GOOGLE_APPLICATION_CREDENTIALS_JSON
        value: replace_this_with_json_string